In [11]:
''' # Q1. Load the given retail sales dataset into a Pandas DataFrame and display the first 5 rows along with the
dataset information to understand its structure.'''
import pandas as pd
df=pd.read_csv("retail_dataset.csv")
df.head(5)
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 7 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Transaction ID    100 non-null    object
 1   Customer ID       100 non-null    object
 2   Product Category  97 non-null     object
 3   Quantity          98 non-null     float64
 4   Price             95 non-null     float64
 5   Date              100 non-null    object
 6   Region            98 non-null     object
dtypes: float64(2), object(5)
memory usage: 5.6+ KB

In [9]:
'''Q2. Inspect the dataset and identify missing values in each column. Display the total number of missing
values present in the dataset.
'''
df.isnull().sum().sum()

np.int64(12)

In [18]:
'''Q3. Replace missing values in the Quantity and Price columns with their respective mean values using
Pandas.
'''
df["Quantity"]=df["Quantity"].fillna(df["Quantity"].mean())
df
df["Price"]=df["Price"].fillna(df["Price"].mean())
df.isnull().sum()

Transaction ID      0
Customer ID         0
Product Category    3
Quantity            0
Price               0
Date                0
Region              2
dtype: int64

In [22]:
'''Q4. Remove all rows where the Product Category or Region column contains missing values.
'''
df =df.dropna(subset=["Product Category","Region"])
df

,Transaction ID,Customer ID,Product Category,Quantity,Price,Date,Region
0,T001,C015,Books,7.0,167.0,02-02-2023,North
1,T002,C004,Toys,4.0,374.0,17-02-2023,South
2,T003,C033,Furniture,8.0,1059.0,17-05-2024,South
3,T004,C047,Groceries,5.0,304.0,11-02-2024,South
4,T005,C022,Books,7.0,282.0,27-07-2024,West
...,...,...,...,...,...,...,...
95,T096,C036,Furniture,10.0,2901.0,08-08-2023,North
96,T097,C021,Clothing,9.0,1077.0,19-07-2024,North
97,T098,C015,Clothing,7.0,643.0,13-08-2023,North
98,T099,C005,Groceries,9.0,429.0,20-01-2024,South
99,T100,C010,Furniture,8.0,1183.0,07-02-2024,North

In [23]:
df.isnull().sum()

Transaction ID      0
Customer ID         0
Product Category    0
Quantity            0
Price               0
Date                0
Region              0
dtype: int64

In [25]:
'''
Q5. Create a new column called Revenue using NumPy, where:

Revenue = Quantity × Price

Display the updated dataset with the new column.'''
df["Revenue"]=df["Quantity"]*df["Price"]
df

/tmp/ipykernel_6499/1338476582.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["Revenue"]=df["Quantity"]*df["Price"]

,Transaction ID,Customer ID,Product Category,Quantity,Price,Date,Region,Revenue
0,T001,C015,Books,7.0,167.0,02-02-2023,North,1169.0
1,T002,C004,Toys,4.0,374.0,17-02-2023,South,1496.0
2,T003,C033,Furniture,8.0,1059.0,17-05-2024,South,8472.0
3,T004,C047,Groceries,5.0,304.0,11-02-2024,South,1520.0
4,T005,C022,Books,7.0,282.0,27-07-2024,West,1974.0
...,...,...,...,...,...,...,...,...
95,T096,C036,Furniture,10.0,2901.0,08-08-2023,North,29010.0
96,T097,C021,Clothing,9.0,1077.0,19-07-2024,North,9693.0
97,T098,C015,Clothing,7.0,643.0,13-08-2023,North,4501.0
98,T099,C005,Groceries,9.0,429.0,20-01-2024,South,3861.0
99,T100,C010,Furniture,8.0,1183.0,07-02-2024,North,9464.0

In [27]:
'''Q6. Using NumPy, calculate the total revenue generated from all transactions in the dataset.
'''
import numpy as np
np.sum(df["Revenue"])

np.float64(465529.66058002145)

In [29]:
'''Q7. Group the dataset by Product Category and calculate the total revenue generated by each category.
'''
df.groupby("Product Category")["Revenue"].sum()

Product Category
Beauty          27647.000000
Books           29597.938776
Clothing        85006.000000
Electronics     93204.315789
Furniture      129664.526316
Groceries       11978.000000
Sports          34484.000000
Toys            53947.879699
Name: Revenue, dtype: float64

In [36]:
'''Q8. Based on the revenue calculated for each product category, identify the top 3 categories with the
highest revenue and the bottom 3 categories with the lowest revenue
'''
top_3=df.groupby("Product Category")["Revenue"].sum().sort_values(ascending=False)
top_3.head(3)
bottom_3= df.groupby("Product Category")["Revenue"].sum().sort_values(ascending=True)
bottom_3.head(3)

Product Category
Groceries    11978.000000
Beauty       27647.000000
Books        29597.938776
Name: Revenue, dtype: float64

In [42]:
'''Q9. Group the dataset by Region and calculate the total revenue generated in each region. Identify the
region with the highest revenue and the region with the lowest revenue.
'''
Region_revenue=df.groupby("Region")["Revenue"].sum().sort_values(ascending=False)
Region_revenue
highest_region=Region_revenue.idxmax()
highest_region
lowest_region=Region_revenue.idxmin()
lowest_region

'West'

In [52]:
'''Q10. Extract the month from the Date column using Pandas and group the dataset by month to calculate the
total monthly revenue. Also, calculate the mean, median, and standard deviation of the Revenue column
using NumPy.
'''
import pandas as pd
df["Date"].head()
df["Date"]=pd.to_datetime(df["Date"],dayfirst=True)
df["Month"]=df["Date"].dt.month
monthly_revenue = df.groupby("Month")["Revenue"].sum()

print(monthly_revenue)
#2 part of q10
mean_revenue=np.mean(df["Revenue"])
mean_revenue
median_revenue = np.median(df["Revenue"])

print(median_revenue)

std_revenue = np.std(df["Revenue"])

print(std_revenue)

Month
1     43994.000000
2     33028.000000
3     10557.000000
4     57298.526316
5     27915.000000
6     28190.000000
7     47851.292159
8     76958.000000
9     30719.105263
10    38017.000000
11    27662.736842
12    43339.000000
Name: Revenue, dtype: float64
3282.1052631578946
4721.171795257337

/tmp/ipykernel_6499/1752062675.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["Date"]=pd.to_datetime(df["Date"],dayfirst=True)
/tmp/ipykernel_6499/1752062675.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["Month"]=df["Date"].dt.month